BLANK_SLATE_USERNAME = ENV['BLANK_SLATE_USERNAME']
BLANK_SLATE_PASSWORD = ENV['BLANK_SLATE_PASSWORD']
# BLANK_SLATE_USERNAME = Rails.application.credentials.blank_slate[:BLANK_SLATE_USERNAME]
# BLANK_SLATE_PASSWORD = Rails.application.credentials.blank_slate[:BLANK_SLATE_PASSWORD]